### PR TITLE
enable ssh pipelining

### PR DESCRIPTION
**Pull request by gronke**
Speeds up Ansible deployment.

### CODE REVIEW

**Comment by Ranlvor** [comment]
TODO: Run this, check what it does

**Comment by Ranlvor** [comment]
Tried that on an other project, got

```
ConfigParser.MissingSectionHeaderError: File contains no section headers.
```

**Comment by gronke** [comment]
fixed

**Comment by Ranlvor** [comment]
Great! Faster than my googling.

**Comment by gronke** [comment]
@Ranlvor any news on this old PR? Did you lookup the configuration option?

**Comment by Ranlvor** [comment]
I enabled it, it did not get faster, I disabled it again

**Pull request closed without merging**
